# Generated by Django 5.2.5 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField()),
                ('story', models.TextField()),
                ('character_description', models.TextField()),
                ('background_description', models.TextField()),
                ('character_image_url', models.URLField(blank=True)),
                ('background_image_url', models.URLField(blank=True)),
                ('combined_image', models.ImageField(blank=True, upload_to='combined/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
